name: ARCHE-Ingest

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Ingest Data into ARCHE
    runs-on: ubuntu-latest
    env:
      ARCHE_USER: pandorfer
      ARCHE_PASSWORD: ${{secrets.ARCHE_PASSWORD}}
      ARCHE: https://arche-curation.acdh-dev.oeaw.ac.at/api
      TOPCOLID: https://id.acdh.oeaw.ac.at/labasi

    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Fetch Data
      run: ./fetch_data.sh
    - name: run metadata import
      run: ./arche__ingest_md.sh
    # - name: run binary_import
    #   run: ./arche__ingest_binaries.sh
    
        